// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.4.0")]
public sealed partial class CreateASPIdentity : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(CreateASPIdentity));
    
    string IMigrationMetadata.Id
    {
        get { return "201912230002208_CreateASPIdentity"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
